language: node_js
node_js:
  - "9"

services:
  - postgresql

services:
  - postgresql

before_script:
  - psql -c 'create database codesling;' -U postgres
  - yarn buildEnv
  - yarn setup:rest-server
  - yarn setup:socket-server
  - yarn setup:services/coderunner-service
  - createuser root
  - yarn db:setup:rest-server

script:
  - yarn start &
  - sleep 10
  - yarn test:socket-server
