language: node_js
node_js:
  - "node"

before_script:
  - yarn add jest
script: jest

env:
  - NODE_ENV=DEVELOPMENT
  - DEBUG=TRUE
  - HOST=http://localhost
  - PORT=4155
  - REST_SERVER_URL=http://localhost:4990
  - CODERUNNER_SERVICE_URL=http://localhost:4000
  - TOKEN_SECRET=codeslinger

