language: node_js
node_js:
  - "9"

services:
  - postgresql

cache:
  directories:
    - node_modules

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    local_dir: dpl_cd_upload
    skip_cleanup: true
    on: &2
      repo: Pot4to/codesling.io-api
    bucket: aaronbucket123
    region: us-west-1
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: aaronbucket123
    key: latest_api.zip
    bundle_type: zip
    application: codesling
    deployment_group: codesling
    region: us-west-1
    on: *2

before_script:
  - psql -c 'create database codesling;' -U postgres
  - psql -c "create user root with superuser password '';" -U postgres
  - yarn buildEnv
  - yarn setup:rest-server
  - yarn setup:socket-server
  - yarn setup:services/coderunner-service
  - yarn db:setup:rest-server

script:
  - yarn start &
  - sleep 10
  - yarn test:socket-server
  - find . -type d -name "*node_modules*" -prune -o -type f -print | zip latest.zip -@
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip
