language: node_js
node_js:
  - "9"

services:
  - postgresql

before_script:
  - psql -c 'create database codesling;' -U postgres
  - yarn buildEnv
  - yarn setup:rest-server
  - yarn setup:socket-server
  - yarn setup:services/coderunner-service
  - yarn db:setup:rest-server

script: yarn test:socket-server

services:
  - postgresql
